# Title: config.yaml
# Author: Guyuan TANG

# Description: this is the config file describing the chagable parameters in the workflow

# specify the location where you downloaded the workflow
workdir: '/home/researcher/TangGY/BINP52/Workflow/Draft/'


# specify the sample list to be used
samples: 'config/All_samples.tsv'

# specify the name of the output directory (Please remember to add the '/' at the end!)
outputdir: 'results/'


bwa_mapping:
  threads: 24


# method to generate the copy number profiles (either rascal
CN_method: rascal


# QDNAseq setting (binsize could be selected from 1, 5, 10, 15, 30, 50, 100,etc., the unit should be kb)
QDNAseq:
  binsize: 100
  # the maximum size of data running in R programme (unit: Mb)
  # for 1kb, it recommends to use at least 2 Gb (2048Mb)
  maxSize: 850
  # the number of threads in running QDNAseq, it will matter how many jobs running in parallel in Snakemake pipeline
  # for binsize <= 15kb, it recommends to operate no more than 2 jobs at a same time to avoid potential errors
  # number of jobs in parallel: total cores / threads
  threads: 3


# Rascal setting (min cellularity and other settings)
Rascal:
  min_cellularity: 0




###### Settting for the second part of the workflow #######
# specify the tsv file contaning samples and their relative copy number solutions derived from the first part of the workflow (Snakefile_solution.smk)
samp_solutions: 'config/solution_tumor.tsv'

# path to the cnsignature scripts
cnsig_path: 'workflow/scripts/cnsignatures/'

# specify the downloaded and decompressed supplement tables for PanCancer signatures
## the folder name after unzip
supple_folder: 'resources/PanCan/'
## the required supplement table
supple_tab: 'resources/PanCan/Supplementary Tables 15-22.xlsx'

# specify the threads for Battenberg to run
battenberg_threads: 30








